print('분과 비교, 논리 연산자')
print(True)
print(False)

print(3 > 1)
print(10 == 10)
print(10 != 10)
print()

print('문자열 비교하기')
print('Python' == 'Python')
print('Python' == 'python')
print('Python' != 'python')
print()

print('정수, 실수, 문자열을 bool 값으로 만들기')
print('정수, 실수의 경우')
print(bool(1))
print(bool(1000202))
print(bool(0))
print(bool(-1))
print(bool(-1.24))

print('문자형의 경우')
print(bool(''))
print(bool(""))
print(bool('hi'))
print(bool("haha"))
